import libtbx.load_env
import os

Import("env_etc")

env_etc.ncdist_dist = os.path.abspath(os.path.join(libtbx.env.dist_path("boost"),"../ncdist"))
if os.path.isdir(env_etc.ncdist_dist):
    env_etc.ncdist_common_includes = [
      env_etc.ncdist_dist,
    ]

if (not env_etc.no_boost_python):
  Import("env_cctbx_boost_python_ext")
  env_ncdist = env_cctbx_boost_python_ext.Clone()
  env_ncdist.Prepend(LIBS=["cctbx"])

  dist_dir = libtbx.env.dist_path("cctbx")
  sourcedir = os.path.join(dist_dir,"uctbx","determine_unit_cell")
  if os.path.isfile(os.path.join(sourcedir,"NCDist.h")):
    env_ncdist.SharedLibrary(target="#lib/determine_unit_cell_ext",
                    source=["ext.cpp",]
    )
  env_etc.include_registry.append(
    env=env_ncdist,
    paths=env_etc.ncdist_common_includes)
  Export("env_ncdist")
